# Generated by Django 3.2.9 on 2021-11-19 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_code', models.CharField(choices=[('one', 'BT 01'), ('two', 'BT 02'), ('three', 'BT 03'), ('four', 'BT 04'), ('five', 'BT 05'), ('six', 'BT 06')], max_length=100)),
                ('first_name', models.CharField(max_length=30, unique=True)),
                ('last_name', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('phone_no', models.DecimalField(decimal_places=5, max_digits=12)),
                ('departure_time', models.DateField()),
                ('return_date', models.DateField()),
                ('pickup_add', models.TextField()),
                ('drop_add', models.TextField()),
                ('vhical_type', models.CharField(choices=[('car', 'CAR $60 per day'), ('bike', 'BIKE $40 dollar per day'), ('small coach', 'SMALL COACH $70 per day'), ('coach', 'COACH $100 per day')], max_length=100)),
                ('num_passenger', models.IntegerField(default=1)),
                ('additional_msg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.ImageField(upload_to='pics')),
                ('contact', models.CharField(max_length=20)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Horizon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('url_field', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HotTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('img', models.ImageField(height_field='image_height', upload_to='Tour', width_field='image_width')),
                ('image_height', models.PositiveIntegerField(blank=True, default='366', editable=False, null=True)),
                ('image_width', models.PositiveIntegerField(blank=True, default='600', editable=False, null=True)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Swipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(height_field='image_height', upload_to='swipper', width_field='image_width')),
                ('image_height', models.PositiveIntegerField(blank=True, default='1920', editable=False, null=True)),
                ('image_width', models.PositiveIntegerField(blank=True, default='678', editable=False, null=True)),
                ('description', models.TextField()),
                ('caption', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(height_field='image_height', upload_to='Tour', width_field='image_width')),
                ('image_height', models.PositiveIntegerField(blank=True, default='420', editable=False, null=True)),
                ('image_width', models.PositiveIntegerField(blank=True, default='368', editable=False, null=True)),
            ],
        ),
    ]
