# Generated by Django 3.2.9 on 2021-11-19 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourApps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horizon',
            name='url_field',
        ),
    ]
