# Generated by Django 3.2.9 on 2021-11-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourApps', '0002_remove_horizon_url_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
