# Generated by Django 3.2.9 on 2021-11-24 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourApps', '0003_customlogin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomLogin',
            new_name='CustomLoginModel',
        ),
    ]
